#!/bin/sh
#---------------------------------------------------------------------
# Description: Script to dump machine details.
#---------------------------------------------------------------------

echo "XXX:--------------------------------------------------"
echo "XXX: $0: Memory details"
echo
cat /proc/meminfo
echo

echo "XXX:--------------------------------------------------"
echo "XXX: $0: ulimit details"
echo
ulimit -a
echo

echo "XXX:--------------------------------------------------"
echo "XXX: $0: CPU count"
echo
grep -c ^processor /proc/cpuinfo

echo

echo "XXX:--------------------------------------------------"
echo "XXX: $0: CPU details"
echo

# show first CPU only
awk 'BEGIN { RS=""; } { printf ("%s\n", $0); exit (0); }' /proc/cpuinfo
echo

kvm=$(cat /sys/module/kvm_intel/parameters/nested 2>/dev/null || echo N)

echo "XXX:--------------------------------------------------"
echo "XXX: $0: Nested KVM support"
echo
echo "$kvm"
echo

echo "XXX:--------------------------------------------------"
echo "XXX: $0: uname"
echo
uname -a
echo

echo "XXX:--------------------------------------------------"
echo "XXX: $0: kernel modules"
echo
lsmod|sort
echo

echo "XXX:--------------------------------------------------"
echo "XXX: $0: distro details"
echo
cat /etc/os-release 2>/dev/null
cat /etc/lsb-release 2>/dev/null
cat /etc/issue 2>/dev/null
echo
