#--------------------------------------------------------------------
# Copyright (c) 2021 James O. D. Hunt <jamesodhunt@gmail.com>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#--------------------------------------------------------------------

name: Build procenv in GitHub Actions build environment

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y \
            automake \
            autopoint \
            check \
            expat \
            libapparmor-dev \
            libcap-dev \
            libnuma-dev \
            libselinux1-dev

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          autoreconf -fi
          ./configure
          make -j4
          make check
